### ISSUE TITLE
Support for margins/gutters

### ISSUE THREAD

**Issue by erin-dot-io** [tin-cat/jquery-mosaic#1]
Love this simple plugin, thanks for sharing!

Would be great if there was an easy way to support margins around images.

For example:

![image](https://cloud.githubusercontent.com/assets/1291167/18771112/09e12978-80f1-11e6-925a-592a78704807.png)

Adding padding or a border currently throws off the layout.

Any chance of adding support for this or any suggestions on how to get there myself?

Thanks!

**Comment by tin-cat** [comment]
Hi Erin,

So much thanks for your suggestion! It is indeed a great idea to add this feature. So great, actually, that I’ve just added and released it! Check out the latest version of jQuery Mosaic with support for outer margin and inner gap between elements: http://jquery-mosaic.tin.cat http://jquery-mosaic.tin.cat/

Thanks!

**Comment by erin-dot-io** [comment]
Wow thank you!
