### ISSUE TITLE
add a single-row mode

### ISSUE THREAD

**Issue by nzjrs** [tin-cat/jquery-mosaic#10]
Imagine a scenario when one wants to use jquery-mosaic to show a single row of images with a fixed height. With a small number of images - fewer than required to tile across the width of a wide display, there are some problems;

 * with skip mode and insufficient images cause the entire widget (all images) to be hidden. This must be a bug?
 * with crop mode, the last image is stretched (as expect)

It would be good to have something very close to 'oversize' mode, but with a limit on the total height 'maxContainerHeight', or 'maxNumRows'. This way, with few images on a wide screen mosaic would not dissapear. Meanwhile, with smaller screens, all images would retain the same height.

**Comment by tin-cat** [comment]
Hey! I just added the new maxRowHeightPolicy 'tail' as suggested by @borekl that might solve this problem, give it a try and let me know! Thanks!
