### ISSUE TITLE
bug: all images hidden when insuffient images are provided to fill the width of the container

### ISSUE THREAD

**Issue by nzjrs** [tin-cat/jquery-mosaic#11]
This is more-or-less the same as #10 but perhaps stated more clearly.

If you have a mosaic configured with `$('#mosaic').Mosaic({maxRowHeight: 200, innerGap:5})` and you have (let's say) only 3 square images, and your container is wider than 615 pixels, then *all* images are hidden (due to https://github.com/tin-cat/jquery-mosaic/blob/f32bfb9d2bcf4c54fbea802be68128c0f25c7069/jquery.mosaic.js#L243)

This is probably a bug?

**Comment by tin-cat** [comment]
Hey! I just added the new maxRowHeightPolicy 'tail' as suggested by @borekl that might solve this problem, give it a try and let me know! Thanks!

**Comment by tin-cat** [comment]
You can see the 'tail' policy working here:
http://jquery-mosaic.tin.cat/example_maxrowheightpolicy.php?randomSeed=9
