### ISSUE TITLE
jquery-mosaic not showing all images

### ISSUE THREAD

**Issue by borekl** [tin-cat/jquery-mosaic#12]
Demos looked nice, so I put together very simple CodePen test:

[https://codepen.io/cenozoic/full/WXLBZB/](https://codepen.io/cenozoic/full/WXLBZB/)

There are 5 (same) images in it. But jquery-mosaic shows sometimes 3, sometimes 4, almost never all 5 (just resize the viewport to see this). That looks pretty unusable for a gallery.

**Comment by tin-cat** [comment]
Hey Borek, take a deeper look to the documentation, that’s a the expected behavior, and you can even control it.

**Comment by sebbean** [comment]
@borekl sounds responsive!

**Comment by borekl** [comment]
@tin-cat Oh, I stand corrected, I didn't realize that 'skip' is the default. BTW, how about implementing another policy 'tail' that would leave the last row not fully filled (with the height at maxRowHeight)?

**Comment by borekl** [comment]
@tin-cat Oh, I stand corrected, I didn't realize that 'skip' is the default. BTW, how about implementing another policy 'tail' that would leave the last row not fully filled (with the height at maxRowHeight)?

**Comment by tin-cat** [comment]
Hi @borekl, I agree! That new policy for the maxRowHeight parameter would be nice to have! Will have a try at i! Thanks!

**Comment by tin-cat** [comment]
Hi! I added a new maxRowHeight policy called 'tail' just as you suggested, I think it works, give it a try and let me know! You can see it working here:

http://jquery-mosaic.tin.cat/example_maxrowheightpolicy.php?randomSeed=9

**Comment by borekl** [comment]
@tin-cat Great! Thanks for implementing this, I am moving to your tiling code (over from perfect-layout).

**Comment by tin-cat** [comment]
Great @borekl! First give it a try to see if the new 'tail' policy works well, I did some tests and it seems to work well, but it's a fresh implementation and should be thoroughly tested before releasing it officially! Also, let us know the URL where you're implementing it so we can see it in action! :D
