### ISSUE TITLE
'data-high-res-image-src' doesn't work for nested elements

### ISSUE THREAD

**Issue by Matysh** [tin-cat/jquery-mosaic#14]
My gallery looks like this:

```
<div class="gallery">
   <div class="gallery-item-img-wrapper"  data-aspect-ratio="1.5">
      <a href="/images/phocagallery/wedding/IMG_8994.jpg">
         <img itemprop="thumbnail" class="gallery-item-img lazyload" src="/images/phocagallery/wedding/thumbs/phoca_thumb_m_IMG_8994.jpg" />
      </a>
   </div>
   ...
   ...
   ...
</div>
```
This structure is due to many factors and I cannot change it. The problem is that 'data-high-res-image-src' property does not work with this structure. I resolve this issue via pretty library '[lazysizes](https://github.com/aFarkas/lazysizes)', but it'll be cool if it works out of the box.

**Comment by tin-cat** [comment]
Hi Matysh, I understand the problem. At this point jquery-mosaic only uses the data-high-res-image-src and data-high-res-background-image-src when applied on each item. That is, each one of the HTML elements in the DOM immediately inside your main Mosaic element. In your case, that would be the "gallery-item-img-wrapper" divs inside the "gallery" div.

I'm afraid what you're suggesting would imply the search for elements with data-high-res-image-src or data-high-res-background-image-src attributes and change them, no matter how deep in the DOM they are. I think that would be a little overkill, as this is a problem that should first be addressed by arranging your HTML and CSS in such a way the item elements in your mosaic are the IMGs itself, or DIVs with the desired background image.

There is also another option that might help you solve this issue: When jquery-mosaic detects the need for a high resolution image, it adds the CSS class "highRes" to the item elements. You can use that to apply different CSS styling to items in high resolution, which could be used, for example, to also change the background image of an item (sadly, not to change an IMG src, as srcs are not specified in CSS). Such case, I'm afraid, would also imply to change your HTML structure.

If more people thinks this could be a useful option for them, please let us know here and I will consider implementing a solution. A nice pull request with a solution will also be appreciated!

Thanks!
