### ISSUE TITLE
Images appear stretched on mobile

### ISSUE THREAD

**Issue by shantamg** [tin-cat/jquery-mosaic#15]
On desktop, making browser skinny like a phone looks good. One image per row. On actual iPhone, the images are stretched (wrong height).

**Comment by shantamg** [comment]
It fixes itself after a refresh so I think the issue happens when images are not fully loaded when the library is called.

**Comment by shantamg** [comment]
perhaps better to use $(window).load() instead of $(document).ready() ?

**Comment by shantamg** [comment]
what I am doing is setting the opacity of the containing div to 0 in css, then inside $(window).load() call Mosaic() and also animate the opacity to 1. Has a nice effect and it keeps the image from snapping from one size to the new size.

**Comment by tin-cat** [comment]
Hi! It's difficult to diagnose the problem you're having without being able to see it, but I would swear it's something related to jquery-mosaic being called before the dom is ready. Be sure you're calling it inside $(window).ready(). If you're manually specifying aspect ratios (data-aspect-ratio), you don't need to wait until the images are loaded. Cheers!

**Comment by tin-cat** [comment]
Closing it as no more feedback received in order to diagnose the problem.

**Comment by shantamg** [comment]
Sorry for not responding. I was very satisfied with the solution I came up with. Thanks for a great piece of software!
