### ISSUE TITLE
[Doc] Specify jquery version compatibility

### ISSUE THREAD

**Issue by BenTalagan** [tin-cat/jquery-mosaic#18]
Hi,

jQuery mosaic may behave badly if not using a recent version (jquery 3.0 at least, it seems to me), because of the following function : 

```javascript
		base.retrieveBaseWidth = function() {
			baseWidth = Math.floor($(base.el).width());
		}
```

With older versions of jquery, the width could be rounded up if floating, so this function could return a bad value (1 pixel too big) and break the whole logic of jquery mosaic. (See here for details about the history of jquery width and floating values [https://github.com/jquery/jquery/issues/1724](https://github.com/jquery/jquery/issues/1724)).

So either this problem should be handled directly in jquery mosaic, or the minimal required version of jquery to use should be specified in the documentation ; old versions of jquery are still used in wordpress for example... :(

Cheers, 
Ben

**Comment by tin-cat** [comment]
Thanks for noting this! Taking a look at it now!

**Comment by tin-cat** [comment]
Done!
