### ISSUE TITLE
Problem with innerGap at some widths

### ISSUE THREAD

**Issue by marcin-jedynski** [tin-cat/jquery-mosaic#19]
I am experiencing a probllem with rendering the mosaic at certain widths. It resides within bootstrap 3 column if that makes any difference. There's video in the link with recording of this happening:

https://www.youtube.com/watch?v=2aOXHqlYcaU

code of the page below:
```
<div class="row">
  <div class="col-lg-8">
   <div class="service-mosaic">
        <div id="civil-engineering-mosaic" class="mosaic">
        <div class="item withImage highRes" width="4032" height="3024" style="background-image: url(/user/pages/04.civil-engineering/zDZhsOW8SKjT3C4.jpg);"></div>
        <div class="item withImage highRes" width="4032" height="3024" style="background-image: url(/user/pages/04.civil-engineering/l7mKy59IRbo6CGa.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/7eZsOJT4IqchSwA.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/T7fINOSB6EP5qD8.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/RvnP5VDlE9SU1gL.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/QnxoLBX3HEpDcTl.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/m0AViw3yOBEjhT2.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/3iDTE41W2zHC0NU.jpg);"></div>
        <div class="item withImage highRes" width="1200" height="1600" style="background-image: url(/user/pages/04.civil-engineering/AdvwU82G4s10fmz.jpg);"></div>
        <div class="item withImage highRes" width="4032" height="3024" style="background-image: url(/user/pages/04.civil-engineering/4LRUnqvT6dJaFMu.jpg);"></div>
   </div>

   <script>
   $(function() {
   $('#civil-engineering-mosaic').Mosaic({
   innerGap: 30,
   outerMargin: 46,
   maxRowHeight: 320,
   maxRowHeightPolicy: 'crop'
   });
   });
    
   </script>
    
  </div>
 </div>

```

**Comment by tin-cat** [comment]
Hi! Sorry I haven't seen this until now!

Thanks for the video, really helps to see the problem! Are you using the latest 0.15 version of jQuery Mosaic? There was a bug related to floating points that have been solved on that release and that caused similar problems.

Also, it seems the mosaic is working fine for the first seconds, then it stops working. I might be wrong, but could it be that some other code in your page is generating a javascript error at some point, and thus stopping jQuery mosaic from updating the mosaic when you keep on resizing? Check out the "Console" tab on your browser to check this.

Let me know! Cheers!

**Comment by tin-cat** [comment]
Hi again! I'm thinking another reason this could be happening is that the plugin doesn't behaves adequately when the browser is not set at 100% zoom level, this is a known bug that has to be solved yet. In your video I can see you're in developer mode, which zooms out the view to simulate a smaller screen. This could be causing something similar to the zoom bug.

**Comment by tin-cat** [comment]
Hi @marcin-jedynski ! Been going through this bug and I'm reasonably sure it's related to a known jQuery bug when using jQuery versions older than 3.3.0. Are you using at least a 3.3.0 version of jQuery in your example?

If so, could you please test it again using the lastest jQuery?

Here's more info about this issue: https://github.com/tin-cat/jquery-mosaic/issues/7

Thanks!

**Comment by tin-cat** [comment]
Since I'm not getting any answer and it's been a long time, I'm closing this issue.
