### ISSUE TITLE
Disappearing picrutes

### ISSUE THREAD

**Issue by okosurona** [tin-cat/jquery-mosaic#28]
After loading all pictures on some screen dimention last pictures aren't show. For example when i got automaticly created 3 rows from 15 pic where row has 4 pic so there is missing 3 pic (script set this last 3 pic on display none). Is this some of bug or what? How can i fix this?

**Comment by tin-cat** [comment]
Hi @okosurona, seems like the normal behavior for some of the maxRowHeightPolicy settings, have you checked this part of the documentation? Cheers!

**Comment by tin-cat** [comment]
Since I'm not getting any answer and it's been a long time, I'm closing this issue.
