### ISSUE TITLE
 Some security findings

### ISSUE THREAD

**Issue by aileenscott-uleska** [tin-cat/jquery-mosaic#31]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/89ba3568-120d-445c-a5d6-ec11ca13491e/
Thanks.
Aileen

**Comment by tin-cat** [comment]
Reporting as spam.
