### ISSUE TITLE
Moving away from jQuery

### ISSUE THREAD

**Issue by borekl** [tin-cat/jquery-mosaic#33]
Any chance if getting rid of the jQuery dependency? These days most new projects don't use jQuery anymore, so it would be nice to avoid depending on it.

**Comment by tin-cat** [comment]
Hi @borekl, that's a great suggestion, and I would love to see someone migrating jQuery Mosaic to vanilla Javascript, unfortunately I do not have plans on doing so.

**Comment by borekl** [comment]
I might attempt that when I get some time.
