### ISSUE TITLE
jquery-mosaic and infinite-scroll Drop down to Second page on chrome dont work

### ISSUE THREAD

**Issue by metalbug** [tin-cat/jquery-mosaic#8]
just chrome dont work, IE and FF it work, you can fix this? thanks man, this plugin so good.

**Comment by tin-cat** [comment]
Hi Metalbug, can you please give more information on how you're doing the infinite scroll you mention on the title of your message? Please bear in mind that the plugin won't work properly if you modify the DOM to add new items (which seems to be what you might be doing with that infinite scroll thing). If that's the case, you'll have to take a look a the code and figure out a way of re-building the mosaic each time the DOM is modified.

**Comment by tin-cat** [comment]
Closing this issue as no more information has been provided by @metalbug after a long time.
