### ISSUE TITLE
All inner items are 100% instead of tiles

### ISSUE THREAD

**Issue by Codevz** [tin-cat/jquery-mosaic#9]
Hi, 

Not sure where is problem, but for me not work correctly. 

Please check this: https://drive.google.com/file/d/0B-xpN57F9sqza0RNNTJBSk1fRUE/view?usp=drivesdk

**Comment by tin-cat** [comment]
Hi Codevz, please take a look at the documentation of the plugin and follow all the instructions there, it seems like you're not loading properly the plugin, or by some reason it's not executing correctly. Not much that I can do with just a screenshot. You can start debugging this problem by looking at the console of your browser.
